/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.clevertec;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class StringUtilsTest {
    @Test
    void isPositiveNumberShouldBeTrue() {
        Assertions.assertTrue(StringUtils.isPositiveNumber("1"));
    }
    @Test
    void isPositiveNumberShouldBeFalse() {
        Assertions.assertFalse(StringUtils.isPositiveNumber("-1"));
    }
    @Test
    void isPositiveNumberShouldBeFalseByException() {
        Assertions.assertFalse(StringUtils.isPositiveNumber(null));
    }
}
